# Phishing URL Detection
## Importing Data

In [30]:
# https://pandas.pydata.org/docs/reference/index.html
import pandas as pd

#loads the CSV file and stores it as "df" or Data Frame
df = pd.read_csv("dataset/malicious_phish.csv")
#gives us the size of the table
print(df.shape)
#tells us what data types are in each column
print(df.dtypes)
#counts the missing values if there are any
print(df.isna().sum())
#counts the amount of each value appear in the data
print(df["type"].value_counts())
#shows 10 random rows as an example
df.sample(10)

(651191, 2)
url     object
type    object
dtype: object
url     0
type    0
dtype: int64
type
benign        428103
defacement     96457
phishing       94111
malware        32520
Name: count, dtype: int64

                                                      url        type
231026  wiki.answers.com/Q/Is_Michiru_and_Haruka_cousi...      benign
579614  www2.beautyblog.com.ua/wp-content/plugins/simi...      benign
194437  en.wikipedia.org/wiki/Category:14th-century_Fr...      benign
225240  http://techcrunch.com/2015/04/22/taxi-app-hail...      benign
211705     http://ptcanoas.com.br/pt-canoas/noticias.html  defacement
289634  archive.org/stream/lifeandlettersj01wintgoog/l...      benign
165713           diplomaframe.com/umkc/school-of-law.aspx      benign
494643  espn.go.com/mma/fighter/_/id/1156/anthony-njok...      benign
361085  https://medium.com/life-learning/the-best-advi...      benign
370126                           foslimited.com/HOME.html      benign

## Cleaning Data

In [31]:
#uses "dropna" to get rid of any missing entrys
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html#
df = df.dropna(subset=["url", "type"])
#turns all values in the URL colomn into strings and then removes spaces, tabs and other stuff so that it make it easier to read
df["url"] = df["url"].astype(str).str.strip()
#creates a column of bool values where True is a URL that has text and False are just blank
df = df[df["url"] != ""]
#strips the www. off the urls so its easier to read
df["url"] = df["url"].replace('https://', '').replace('http://', '').replace('www.', '')
df.sample(10)

                                                      url        type
579595  tkconstitution.tk/modules/mod_wrapper/tk/ms/te...      benign
537308                http://115.229.250.129:53660/Mozi.m     malware
351894  http://www.platingroup.az/en/telim-teqvimi/day...  defacement
278020  blogs.guardian.co.uk/arts/author/kitty_empire/...      benign
83034                                   orrsbutchers.com/      benign
517382                           musotica.com/seg0da.html      benign
245869          mrbreakfast.com/r_display.asp?restid=1324      benign
538138                       http://5.252.179.60/b/armv7l     malware
338342                merriam-webster.com/dictionary/rant      benign
448769  prnewswire.com/news-releases/mefeedia-launches...      benign

In [32]:
#use "map" to assign a int to each type so that it is easier to sort and understand
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html
df["type"] = df["type"].map({"phishing": 0, "benign": 1, "defacement": 2, "malware": 3})
#cleans out all the rows that arnt in the dictionary above
df = df.dropna(subset=["type"])
#converts all the types to int incase any werent
df["type"] = df["type"].astype(int)
#gives me a test sample to see if the map worked
df.sample(10)

                                                      url  type
560561  'services-runescape-com-sl-forums.totalh.net/s...     1
85951                 hipsterrunoff.com/topic/arcade-fire     1
429675         canadavisa.com/about-british-columbia.html     1
537704     http://142.93.159.72/Anti_Bins/Antisocial.m68k     3
542671                     http://59.125.190.210:56936/.i     3
267995                           happyfathersdaydaddy.com     0
533906  https://poderdafala.com.br/InterAcessoCliente/...     0
500265  artscipub.com/repeaters/dsprpts.asp?state=cali...     1
352020  facebook.com/people/Ballymena-HockeyClub/10000...     1
178590  http://teespring.com/en-GB/atp-shirt?utm_campa...     1

## Machine Learning model

In [33]:
#gets the function that will split the data into the training set and the test set
#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split
#
#from sklearn.feature_extraction.text import TfidfVectorizer
#gets the Random Forest model that make a collection of decision trees that vote of the best answer
#https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html 
from sklearn.ensemble import RandomForestClassifier
#
#from sklearn.metrics import classification_report