In [54]:
import pandas as pd

#loads the CSV file and stores it as "df" or Data Frame
df = pd.read_csv("dataset/malicious_phish.csv")
#gives us the size of the table
print(df.shape)
#tells us what data types are in each column
print(df.dtypes)
#counts the missing values if there are any
print(df.isna().sum())
#counts the amount of each value appear in the data
print(df["type"].value_counts())
#shows 10 random rows as an example
df.sample(10)

(651191, 2)
url     object
type    object
dtype: object
url     0
type    0
dtype: int64
type
benign        428103
defacement     96457
phishing       94111
malware        32520
Name: count, dtype: int64

                                                      url        type
534067                   http://detes.sk/1122//?sec=Susan    phishing
40543         dicionario.sensagent.com/teapot+rock/en-en/      benign
448420                           imdb.com/name/nm0267511/      benign
172503  http://www.besztercekk.hu/index.php?option=com...  defacement
17885   http://www.5068.com/uploads/allimg/130821/81_1...     malware
104518  baseballcardshopper.com/Topps_Bowman_Fleer_Don...      benign
348569  manta.com/ic/mtq5dvt/ca/entreprises-lucien-goy...      benign
574261  cmsol.com.au/templates/yoo_core/lib/php/pay_fo...      benign
335463                     utexas.edu/world/comcol/state/      benign
623230                        tools.ietf.org/html/rfc2183    phishing

In [55]:
#uses "dropna" to get rid of any missing entrys
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html#
df = df.dropna(subset=["url", "type"])
#turns all values in the URL colomn into strings and then removes spaces, tabs and other stuff so that it make it easier to read
df["url"] = df["url"].astype(str).str.strip()
#creates a column of bool values where True is a URL that has text and False are just blank
df = df[df["url"] != ""]

In [ ]:
#use "map" to assign a int to each type so that it is easier
df["type"] = df["type"].map({"phishing": 0, "benign": 1, "defacement": 2, "malware": 3})
df.sample(10)

                                                      url  type
544716  https://apbfiber.com/openme/12020d200d42d3_18d...     3
258244  homepage.mac.com/rriopel/RiopelRiopelle/fg_idx...     1
391645  http://www.plasmatreatment.co.uk/index.php/pla...     2
387775  http://www.simmeurope.com/index.php?view=artic...     2
122452                               mylife.com/tjreilly1     1
47672           http://www.yyjanet.com/about/Default.aspx     2
413539            afterhourspotomacsept22.eventbrite.com/     1
372837                          soccercampsofamerica.com/     1
395246  http://cignetfund.com/index.html?keepThis=true...     2
235125  http://www.barbosacooper.com.br/site/index.php...     2